### ISSUE TITLE
Linux errors

### ISSUE THREAD

**Issue by neuxell** [TDTW/teeworlds#3]
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/engine/server/server_d.o' error 256
[ 4/28] #1 c++ src/game/server/gamecontroller.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/gamecontroller.cpp:10:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/gamecontroller_d.o' error 256
[ 5/28] #1 c++ src/game/server/player.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/player.h:8,
                 from src/game/server/player.cpp:5:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/player_d.o' error 256
[ 6/28] #1 c++ src/game/server/entity.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/entity.cpp:5:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/entity_d.o' error 256
[ 7/28] #1 c++ src/game/server/gamemodes/ctf.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/player.h:8,
                 from src/game/server/gamemodes/ctf.cpp:9:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/gamemodes/ctf_d.o' error 256
[ 8/28] #1 c++ src/game/server/gamemodes/tdm.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/player.h:8,
                 from src/game/server/gamemodes/tdm.cpp:6:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/gamemodes/tdm_d.o' error 256
[ 9/28] #1 c++ src/game/server/entities/laser.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/entities/laser.cpp:4:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/entities/laser_d.o' error 256
[10/28] #1 c++ src/game/server/entities/flag.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/entities/flag.cpp:3:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/entities/flag_d.o' error 256
[11/28] #1 c++ src/game/server/entities/character.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/entities/character.cpp:5:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_KillMsg]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
bam: 'objs/game/server/entities/character_d.o' error 256
[12/28] #1 c++ src/game/server/entities/pickup.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/entities/pickup.cpp:4:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/entities/pickup_d.o' error 256
[13/28] #1 c++ src/game/server/entities/projectile.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/entities/projectile.cpp:4:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/entities/projectile_d.o' error 256
[14/28] #1 c++ src/game/server/gamecontext.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/gamecontext.cpp:8:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_SoundGlobal]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_Chat]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_Emoticon]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_WeaponPickup]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_Broadcast]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_VoteSet]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_VoteStatus]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_Motd]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_VoteClearOptions]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_VoteOptionListAdd]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_ReadyToEnter]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_VoteOptionAdd]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool) [with T = CNetMsg_Sv_VoteOptionRemove]’:
src/engine/server.h:46:2: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
bam: 'objs/game/server/gamecontext_d.o' error 256
[15/28] #1 c++ src/game/server/gameworld.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/gameworld.cpp:6:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/gameworld_d.o' error 256
[16/28] #1 c++ src/game/server/eventhandler.cpp
In file included from src/game/server/gamecontext.h:6:0,
                 from src/game/server/eventhandler.cpp:4:
src/engine/server.h: In member function ‘int IServer::SendPackMsg(T*, int, int, bool, bool)’:
src/engine/server.h:45:58: error: no matching function for call to ‘IServer::SendMsgEx(CMsgPacker*&, int&, int&, bool&, bool&)’
   return SendMsgEx(&Packer, Flags, ClientID, System, Tdtw);
                                                          ^
src/engine/server.h:45:58: note: candidate is:
src/engine/server.h:37:14: note: virtual int IServer::SendMsgEx(CMsgPacker*, int, int, bool)
  virtual int SendMsgEx(CMsgPacker *pMsg, int Flags, int ClientID, bool System);
              ^
src/engine/server.h:37:14: note:   candidate expects 4 arguments, 5 provided
bam: 'objs/game/server/eventhandler_d.o' error 256
[17/28] #1 c++ src/game/client/ui/value.cpp
src/game/client/ui/value.cpp:15:2: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
  m_pOnStartArg = nullptr;
  ^
src/game/client/ui/value.cpp: In constructor ‘CValue::CValue(CNuiElement*)’:
src/game/client/ui/value.cpp:15:18: error: ‘nullptr’ was not declared in this scope
  m_pOnStartArg = nullptr;
                  ^
bam: 'objs/game/client/ui/value_d.o' error 256
[18/28] #1 c++ src/game/client/ui/elements.cpp
src/game/client/ui/elements.cpp:31:2: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
  m_pArgOnClick = nullptr;
  ^
src/game/client/ui/elements.cpp: In constructor ‘CNuiElement::CNuiElement(CNui*, const char*)’:
src/game/client/ui/elements.cpp:31:18: error: ‘nullptr’ was not declared in this scope
  m_pArgOnClick = nullptr;
                  ^
src/game/client/ui/elements.cpp: In member function ‘void CNuiElement::SetCallback(CNuiElement::CALLBACK_TYPE, CNuiElement::CallBack, void*)’:
src/game/client/ui/elements.cpp:125:14: error: ‘nullptr’ was not declared in this scope
   if(pArg != nullptr)
              ^
src/game/client/ui/elements.cpp:131:14: error: ‘nullptr’ was not declared in this scope
   if(pArg != nullptr)
              ^
src/game/client/ui/elements.cpp:137:14: error: ‘nullptr’ was not declared in this scope
   if(pArg != nullptr)
              ^
src/game/client/ui/elements.cpp:143:14: error: ‘nullptr’ was not declared in this scope
   if(pArg != nullptr)
              ^
src/game/client/ui/elements.cpp:149:14: error: ‘nullptr’ was not declared in this scope
   if(pArg != nullptr)
              ^
src/game/client/ui/elements.cpp:155:14: error: ‘nullptr’ was not declared in this scope
   if(pArg != nullptr)
              ^
src/game/client/ui/elements.cpp:161:14: error: ‘nullptr’ was not declared in this scope
   if(pArg != nullptr)
              ^
src/game/client/ui/elements.cpp: In member function ‘void CNuiElement::SetCallbacksEvent(CNuiElement::CallBack, CNuiElement::CallBack, CNuiElement::CallBack, void*)’:
src/game/client/ui/elements.cpp:174:13: error: ‘nullptr’ was not declared in this scope
  if(pArg != nullptr)
             ^
src/game/client/ui/elements.cpp: In member function ‘void CNuiElement::SetCallbacksVisual(CNuiElement::CallBack, CNuiElement::CallBack, CNuiElement::CallBack, CNuiElement::CallBack, void*)’:
src/game/client/ui/elements.cpp:192:13: error: ‘nullptr’ was not declared in this scope
  if(pArg != nullptr)
             ^
bam: 'objs/game/client/ui/elements_d.o' error 256
[19/28] #1 c++ src/game/client/gameclient.cpp
In file included from other/sdl/include/SDL_config.h:42:0,
                 from other/sdl/include/SDL_stdinc.h:30,
                 from other/sdl/include/SDL_joystick.h:30,
                 from src/game/client/components/controls.h:7,
                 from src/game/client/gameclient.cpp:28:
other/sdl/include/SDL_config_minimal.h:38:22: error: conflicting declaration ‘typedef unsigned int size_t’
 typedef unsigned int size_t;
                      ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:146:0,
                 from /usr/include/semaphore.h:22,
                 from src/base/system.h:416,
                 from src/engine/kernel.h:6,
                 from src/engine/editor.h:5,
                 from src/game/client/gameclient.cpp:3:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:212:23: error: ‘size_t’ has a previous declaration as ‘typedef long unsigned int size_t’
 typedef __SIZE_TYPE__ size_t;
                       ^
bam: 'objs/game/client/gameclient_d.o' error 256
[20/28] #1 c++ src/game/client/components/hud.cpp
In file included from other/sdl/include/SDL_config.h:42:0,
                 from other/sdl/include/SDL_stdinc.h:30,
                 from other/sdl/include/SDL_joystick.h:30,
                 from src/game/client/components/controls.h:7,
                 from src/game/client/components/hud.cpp:14:
other/sdl/include/SDL_config_minimal.h:38:22: error: conflicting declaration ‘typedef unsigned int size_t’
 typedef unsigned int size_t;
                      ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:146:0,
                 from /usr/include/semaphore.h:22,
                 from src/base/system.h:416,
                 from src/engine/kernel.h:6,
                 from src/engine/graphics.h:6,
                 from src/game/client/components/hud.cpp:3:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:212:23: error: ‘size_t’ has a previous declaration as ‘typedef long unsigned int size_t’
 typedef __SIZE_TYPE__ size_t;
                       ^
bam: 'objs/game/client/components/hud_d.o' error 256
[21/28] #1 c++ src/game/client/components/controls.cpp
src/game/client/components/controls.cpp:19:20: fatal error: windef.h: No such file or directory
 #include <windef.h>
                    ^
compilation terminated.
bam: 'objs/game/client/components/controls_d.o' error 256
[22/28] #1 c++ src/game/client/components/players.cpp
In file included from other/sdl/include/SDL_config.h:42:0,
                 from other/sdl/include/SDL_stdinc.h:30,
                 from other/sdl/include/SDL_joystick.h:30,
                 from src/game/client/components/controls.h:7,
                 from src/game/client/components/players.cpp:20:
other/sdl/include/SDL_config_minimal.h:38:22: error: conflicting declaration ‘typedef unsigned int size_t’
 typedef unsigned int size_t;
                      ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:146:0,
                 from /usr/include/semaphore.h:22,
                 from src/base/system.h:416,
                 from src/engine/kernel.h:6,
                 from src/engine/demo.h:6,
                 from src/game/client/components/players.cpp:3:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:212:23: error: ‘size_t’ has a previous declaration as ‘typedef long unsigned int size_t’
 typedef __SIZE_TYPE__ size_t;
                       ^
bam: 'objs/game/client/components/players_d.o' error 256
[23/28] #1 c++ src/game/client/components/console.cpp
In file included from other/sdl/include/SDL_config.h:42:0,
                 from other/sdl/include/SDL_stdinc.h:30,
                 from other/sdl/include/SDL_joystick.h:30,
                 from src/game/client/components/controls.h:7,
                 from src/game/client/components/console.cpp:26:
other/sdl/include/SDL_config_minimal.h:38:22: error: conflicting declaration ‘typedef unsigned int size_t’
 typedef unsigned int size_t;
                      ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:146:0,
                 from /usr/include/semaphore.h:22,
                 from src/base/system.h:416,
                 from src/game/client/components/console.cpp:7:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:212:23: error: ‘size_t’ has a previous declaration as ‘typedef long unsigned int size_t’
 typedef __SIZE_TYPE__ size_t;
                       ^
bam: 'objs/game/client/components/console_d.o' error 256
[24/28] #1 c++ src/game/client/components/nameplates.cpp
In file included from other/sdl/include/SDL_config.h:42:0,
                 from other/sdl/include/SDL_stdinc.h:30,
                 from other/sdl/include/SDL_joystick.h:30,
                 from src/game/client/components/controls.h:7,
                 from src/game/client/components/nameplates.cpp:11:
other/sdl/include/SDL_config_minimal.h:38:22: error: conflicting declaration ‘typedef unsigned int size_t’
 typedef unsigned int size_t;
                      ^
In file included from /usr/include/x86_64-linux-gnu/sys/types.h:146:0,
                 from /usr/include/semaphore.h:22,
                 from src/base/system.h:416,
                 from src/engine/kernel.h:6,
                 from src/engine/textrender.h:5,
                 from src/game/client/components/nameplates.cpp:3:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:212:23: error: ‘size_t’ has a previous declaration as ‘typedef long unsigned int size_t’
 typedef __SIZE_TYPE__ size_t;
                       ^
bam: 'objs/game/client/components/nameplates_d.o' error 256
[25/28] #1 c++ src/game/client/components/camera.cpp
In file included from other/sdl/include/SDL_config.h:42:0,
                 from other/sdl/include/SDL_stdinc.h:30,
                 from other/sdl/include/SDL_joystick.h:30,
                 from src/game/client/components/controls.h:7,
                 from src/game/client/components/camera.cpp:11:
other/sdl/include/SDL_config_minimal.h:38:22: error: conflicting declaration ‘typedef unsigned int size_t’
 typedef unsigned int size_t;
                      ^
In file included from /usr/include/stdlib.h:32:0,
                 from src/base/math.h:6,
                 from src/game/client/components/camera.cpp:5:
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/stddef.h:212:23: error: ‘size_t’ has a previous declaration as ‘typedef long unsigned int size_t’
 typedef __SIZE_TYPE__ size_t;
                       ^
bam: 'objs/game/client/components/camera_d.o' error 256
[26/28] #1 c++ src/game/client/tdtwserver/tdtwserver.cpp
src/game/client/tdtwserver/tdtwserver.cpp:3:20: fatal error: direct.h: No such file or directory
 #include <direct.h>
                    ^
compilation terminated.
bam: 'objs/game/client/tdtwserver/tdtwserver_d.o' error 256
bam: error: a build step failed

**Comment by Henningstone** [comment]
```
[16/52] #1 c++ src/game/client/components/controls.cpp
src/game/client/components/controls.cpp:19:20: fatal error: windef.h: File or folder not found.
compilation terminated.
```

...windef.h...
Seems to be a windows only client :\

Also those make me doubt multiplatform support:
```
src/game/client/tdtwserver/tdtwserver.cpp:3:20: fatal error: direct.h: File or Folder not found.
compilation terminated.
```

```
src/engine/shared/autoupdate.cpp:112:27: error: ‘rename’ was not declared in this scope
  if (rename(aBuf, FileName))
```

```
src/engine/shared/autoupdate.cpp:115:17: error: ‘system’ was not declared in this scope
  if (system(aBuf))
```

```
src/base/system.c: In function ‘fs_listdir2’:
src/base/system.c:1348:36: error: ‘finddata’ undeclared (first use in this function)
   if ((folder_id == 0 && (str_comp(finddata.cFileName, "data") == 0 ||
```

**Comment by Spoki4** [comment]
Thank you for your issue, I will fix it soon.

**Comment by Spoki4** [comment]
Fixed.
